site_name: Backend Engineering Notes
site_description: Backend architecture, event-driven systems and DevOps patterns
site_author: Aliasoft
extra_css:
  - stylesheets/extra.css

#extra_javascript:
#  - https://unpkg.com/mermaid/dist/mermaid.min.js
plugins:
  - search
  - mermaid2:
      arguments:
        theme: default
extra:
  font:
    text: Inter
    code: JetBrains Mono

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.tasklist

theme:
    name: material
    favicon: null
    logo: null
    features:
      - navigation.tabs
      - navigation.sections
      - navigation.expand
      - navigation.top
      - toc.follow
      - content.code.copy
      - search.highlight
      - search.suggest

    palette:
      #  Colors:  blue  indigo  teal  cyan  deep purple
      - scheme: default
        primary: cyan
        accent: cyan
        toggle:
          icon: material/weather-night
          name: Dark mode
      - scheme: slate
        primary: cyan
        accent: cyan
        toggle:
          icon: material/weather-sunny
          name: Light mode


nav:
    - Home: index.md
    - Architecture:
          - CQRS Pattern: topics/architecture/cqrs-pattern.md
          - Hexagonal Architecture: topics/spring/hexagonal-architecture.md
    - Event Driven Systems:
          - Retry and DLT Pattern: topics/kafka/retry-and-dlt-pattern.md
          - Idempotent Consumers: topics/kafka/idempotent-consumers.md
          - Outbox Pattern: topics/kafka/outbox-pattern.md
          - Reliability Patterns: topics/kafka/reliability-patterns.md
    - Security:
          - JWT Authentication Pattern: topics/security/jwt-authentication-pattern.md
    - DevOps:
          - Docker Production Pattern: topics/devops/docker-production-pattern.md
          - Container Security: topics/devops/container-security.md
          - Reverse Proxy Pattern: topics/devops/reverse-proxy-pattern.md
          - Pull-based Deployment: topics/devops/pull-based-deployment.md
          - CI/CD Pipeline Pattern: topics/devops/ci-cd-pipeline-pattern.md
    - Projects:
          - Seaway Overview: projects/seaway/project-overview.md
          - Architecture Overview: projects/seaway/architecture-overview.md
          - CI/CD Overview: projects/seaway/ci-cd-overview.md
          - Security Overview: projects/seaway/security-overview.md

copyright: >
  © 2026 Aliasoft • Backend Engineering Notes